server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Gestion explicite des types MIME et des fichiers statiques
  location ~* \.(ico|png|jpg|jpeg|gif|svg|js|css)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public, no-transform";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}